---
title: "My Special Dilution Sheet"
output: pdf_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
mainfont: Calibri Light
---

# User Inputs
```{r, echo = F, warning = F, message = F, results = 'asis'}

glue::glue("Version: {version}")
cat('\n')
glue::glue("Food: {food}")
cat('\n')
glue::glue("Dose response: {dose}")
cat('\n')
glue::glue("Minimum amount to pipette: {min}")
cat('\n')
glue::glue("Number of drugs: {drugs}")
cat('\n')
if(dose == T) {
    drug_inputs <- data.frame(drug = NA, drugstock = NA, diluent = NA, drugdose = NA, drugplates = NA, wells = NA)
    for(d in 1:drugs) {
        drug_inputs <- rbind(drug_inputs, c(get(glue::glue("drug_name{d}")),
                             get(glue::glue("drug_stock{d}")),
                             get(glue::glue("control_name{d}")),
                             get(glue::glue("drug_dose{d}")),
                             get(glue::glue("drugplates{d}")),
                             get(glue::glue("wells{d}"))))
    }
    drug_inputs <- drug_inputs %>%
        na.omit() %>%
        dplyr::select(Drug = drug, `Stock Conc. (mM)` = drugstock, Diluent = diluent, `Drug Dose (uM)` = drugdose, `Drug Plates` = drugplates, Wells = wells)
} else {
    drug_inputs <- data.frame(drug = NA, drugstock = NA, diluent = NA, drugdose = NA, drugplates = NA, controlplates = NA, wells = NA)
    for(d in 1:drugs) {
        drug_inputs <- rbind(drug_inputs, c(get(glue::glue("drug_name{d}")),
                             get(glue::glue("drug_stock{d}")),
                             get(glue::glue("control_name{d}")),
                             get(glue::glue("drug_dose{d}")),
                             get(glue::glue("drugplates{d}")),
                             get(glue::glue("controlplates{d}")),
                             get(glue::glue("wells{d}"))))
    }
    drug_inputs <- drug_inputs %>%
        na.omit() %>%
        dplyr::select(Drug = drug, `Stock Conc. (mM)` = drugstock, Diluent = diluent, `Drug Dose (uM)` = drugdose, `Drug Plates` = drugplates, `Control Plates` = controlplates, Wells = wells)
}

# print drug inputs
knitr::kable(drug_inputs, format = "markdown")

cat('\n')
cat("\n\n\\pagebreak\n")


```

```{r, echo = F, warning = F, message = F, results = 'asis'}

dosetable <- calculate_dose()

```

# Food Setup
```{r, echo = F, warning = F, message = F, results = 'asis'}

lysate_instructions <- dosetable[[2]]
lysate_instructions[1]
cat('\n')
print(lysate_instructions[2])
cat('\n')
print(lysate_instructions[3])
cat('\n')
print(lysate_instructions[4])

```

# Drug Dilutions
```{r, echo = F, warning = F, message = F, results = 'asis'}

rename <- dosetable[[3]]
knitr::kable(rename, format = "markdown")

```

# Plate Dilutions
```{r, echo = F, warning = F, message = F, results = 'asis'}

if(version == "v2") {
    print("Add 50 uL food + drug to wells.")
} else {
    print("Add 25 uL food + drug to wells with 50 uL worms.")
}

if(dose == T) {
    for(d in 1:drugs) {
        table <- dosetable[[1]] %>%
            dplyr::mutate(condition = as.character(condition)) %>%
            dplyr::filter(condition == get(glue::glue("drug_name{d}"))) 
        print(knitr::kable(table, format = "markdown"))
    }
} else {
    table <- dosetable[[1]]
    knitr::kable(table, format = "markdown")
}

```